### ISSUE TITLE
cv2.imwrite(f"image_sequence/{full_image_names[i]}", final_frame) IndexError: list index out of range

### ISSUE THREAD

**Issue by glennford49** [chadlimedamine/Background-Changer#9]
im trying to make python files out of this
it throws error :cv2.imwrite(f"image_sequence/{full_image_names[i]}", final_frame)
IndexError: list index out of range

**Comment by chadlimedamine** [comment]
If you used the same variables as the source code then the index is not supposed to get out of range.
Did you changed any variables?
If all the variables are the same as this code listed below then it is supposed to work perfectly.
```python
full_image_names = []
for i in range(video_length):
    full_image_names.append(f"frame_{i}.jpg")
full_image_names = sorted(full_image_names)
for i, frame in enumerate(clip_copy.iter_frames(dtype = "uint8"), 0):
```

**Comment by glennford49** [comment]
I think did not changing any variables, since i' ve only copied it to .py files, ive tried running it on jupyter to run it directly as ipynb, and it throws error but with imageio, maybe the version im using the cause...
